export enum StateEnum {
  CA = "California",
  TX = "Texas",
  MD = "Maryland",
  OH = "Ohio",
  UT = "Utah",
  NY = "New York",
  WV = "West Virginia",
  GA = "Georgia",
  IN = "Indiana",
  WI = "Wisconsin",
  IL = "Illinois",
  CO = "Colorado",
  MI = "Michigan",
  MA = "Massachusetts",
  VA = "Virginia",
  FL = "Florida",
  OR = "Oregon",
  MO = "Missouri",
  PA = "Pennsylvania",
  AZ = "Arizona",
  TN = "Tennessee",
  KS = "Kansas",
  KY = "Kentucky"
}